### ISSUE TITLE
Develop : Problem 1

### ISSUE THREAD

**Issue by Krishna-coder12** [Krishna-coder12/Project4#1]
As I developed the getting started.html file with the given components as the example. And done both example.jsx and example.css files. And updated the motto-update so that it get reflected in the components in the example directory. Rendered all the react components to the example.jsx file. And updated all the example views according to the requirements.

**Comment by tarunlagadapati25** [comment]
As a Developer i runs the code that it gives a proper output as mentioned above there are no errors that delay the code to get a required output.
